### ISSUE TITLE
我知道要运行pu.py脚本，但我不知道哪里填cookie和学校代码

### ISSUE THREAD

**Issue by iodjjd** [StableAgOH/PUscorespider#1]
我用搜索软件才能查出来哪里填cookie。。。
![Screenshot_1](https://user-images.githubusercontent.com/76802920/103395720-854d8a00-4b6a-11eb-983e-67b5849f1267.png)
建议lz可以参考[超星学习通全自动刷课程序](https://github.com/ZhyMC/chaoxing-xuexitong-autoflush#%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E5%85%A8%E8%87%AA%E5%8A%A8%E5%88%B7%E8%AF%BE%E7%A8%8B%E5%BA%8F)

**Comment by iodjjd** [comment]
> 我用搜索软件才能查出来哪里填cookie。。。
> ![Screenshot_1](https://user-images.githubusercontent.com/76802920/103395720-854d8a00-4b6a-11eb-983e-67b5849f1267.png)
> 建议lz可以参考[超星学习通全自动刷课程序](https://github.com/ZhyMC/chaoxing-xuexitong-autoflush#%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E5%85%A8%E8%87%AA%E5%8A%A8%E5%88%B7%E8%AF%BE%E7%A8%8B%E5%BA%8F)修改下readme.md

**Comment by StableAgOH** [comment]
你好，请先运行`pip install -r requirements.txt`指令安装本项目所需的包，安装好后运行pu.py即可在程序中直接输入Cookie和学校。
config.json会是程序自动生成的，不需要用户创建
README.md已经修改啦

**Comment by Zxilly** [comment]
> 你好，请先运行`pip install -r requirements.txt`指令安装本项目所需的包，安装好后运行pu.py即可在程序中直接输入Cookie和学校。
> config.json会是程序自动生成的，不需要用户创建
> README.md已经修改啦

大佬太强辣，%%%%%%%

**Comment by StableAgOH** [comment]
> > 你好，请先运行`pip install -r requirements.txt`指令安装本项目所需的包，安装好后运行pu.py即可在程序中直接输入Cookie和学校。
> > config.json会是程序自动生成的，不需要用户创建
> > README.md已经修改啦
> 
> 大佬太强辣，%%%%%%%

？？？

**Comment by iodjjd** [comment]
> > > 你好，请先运行`pip install -r requirements.txt`指令安装本项目所需的包，安装好后运行pu.py即可在程序中直接输入Cookie和学校。
> > > config.json会是程序自动生成的，不需要用户创建
> > > README.md已经修改啦
> > 
> > 
> > 大佬太强辣，%%%%%%%
> 
> ？？？

感谢
